export const FONT_FAMILY = 'Roboto, Arial, sans-serif'
export const FONT_SIZE_L = '23px'
export const FONT_SIZE_M = '18px'
export const FONT_SIZE_S = '14px'
export const FONT_SIZE_XL = '29px'
export const FONT_SIZE_XS = '12px'
export const FONT_SIZE_XXL = '36px'
export const FONT_SIZE_XXXL = '45px'
